### ISSUE TITLE
Compiling using the production mode profile fails

### ISSUE THREAD

**Issue by Juchar** [appreciated/progressbar-js#4]
If I compile a vaadin project using the provided `production-mode` profile (use the vaadin starter) then I get the following error:

`[ERROR] error: Error: ENOENT: no such file or directory, open 'C:\Users\xxx\projectpath\target\webjars\progressbar.js\1.0.1\dist\progressbar.js'`

**Comment by appreciated** [comment]
@Juchar just that you know I am planning to abandon this project since [ApexCharts.js also offers circular progressbars](https://vaadin.com/directory/component/apexchartsjs), but also supports much more configuration. Checkout the the [offical code examples](https://apexcharts.com/javascript-chart-demos/radialbar-charts/) for some details.
